### PR TITLE
Ванеев - Лабораторная работа #1 

### PR DESCRIPTION
**Pull request by nikitavaneev**

### CODE REVIEW

**Comment by nikitavaneev** [comment]
@adgluzdov
@pavelbar

**Comment by adgluzdov** [comment]
👍

**Comment by pavelbar** [comment]
:+1:

**Comment by pavelbar** [comment]
👍

**Comment by adgluzdov** [comment]
👍

**Comment by pavelbar** [comment]
@AntonGrishin @sawirani
Hi reviewers,
This is a polite reminder
Merge is needed here
Thanks

**Pull request merged**
