### PR TITLE
Gerasimov - Лабораторная работа #0

### PR DESCRIPTION
**Pull request by GerasimovDG**

### CODE REVIEW

**Comment by GerasimovDG** [comment]
@suntsovsergey
@Trintal

**Comment by suntsovsergey** [comment]
:+1:

**Comment by Trintal** [comment]
:+1:

**Comment by VikaSannikova** [comment]
🥇

**Comment by GerasimovDG** [comment]
@kirill-korniakov

**Comment by AntonGrishin** [comment]
@GerasimovDG please rebase

**Pull request merged**
